package Booking

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	EzyCustomerApi
	EzyStageApi
	EzyBranchApi
	EzyAppointmentApi
	EzyOrdersApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
