package Booking

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	EzyCustomerRouter
	EzyStageRouter
	EzyBranchRouter
	EzyAppointmentRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
